(require 'elfeed)
(elfeed-add-feed "https://sachachua.com/blog/category/emacs/feed/")
;(elfeed-add-feed "https://emacs-china.org/posts.rss")
;(elfeed-add-feed "https://emacs-china.org/latest.rss")
(elfeed-add-feed "https://feeds.appinn.com/appinns")
(elfeed-update)
(provide 'init-elfeed)
